"""Measurement harnesses for TiraLib.

A harness owns the generation of the measurement *wrapper*: the standalone
binary that allocates and initializes the buffers, calls the compiled
Tiramisu function, measures its execution time, and prints the measured
times (in milliseconds) to stdout.

Two harnesses are provided:

- :class:`DefaultHarness` — TiraLib's historical harness: buffers are
  malloc'ed and filled once with a random constant, then the kernel is
  timed ``min_runs``/``max_runs`` times back-to-back in a single process
  with ``std::chrono``.

- :class:`PolybenchHarness` — a PolyBench/C 4.2.1 compatible harness for
  PolyBench-derived Tiramisu programs. Each measurement follows the exact
  PolyBench methodology, in a *fresh process* (like PolyBench's
  ``time_benchmark.sh``): page-aligned allocation via
  ``polybench_alloc_data``, deterministic PolyBench ``init_array``
  initialization (from a per-benchmark generated "init sidecar" header),
  cache flush before starting the timer (``polybench_timer_start``), one
  kernel invocation, ``polybench_timer_stop``. The vendored, unmodified
  PolyBench ``polybench.h``/``polybench.c`` sources are inlined into the
  generated wrapper, so the measurement code is PolyBench's own.

Both harnesses generate a self-contained wrapper that honors the same
execution protocol (``MIN_RUNS``/``MAX_RUNS``/``TIME_BUDGET`` environment
variables, one float per measurement in **milliseconds** on stdout), so
they are interchangeable for both the pure-Python backend
(``CompilingService``) and the TiraLibCpp server backend.
"""

from __future__ import annotations

import logging
import random
import re
from abc import ABC, abstractmethod
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from tiralib.tiramisu.tiramisu_program import TiramisuProgram

logger = logging.getLogger(__name__)

_POLYBENCH_DIR = Path(__file__).parent / "polybench"

#: Maps Tiramisu primitive type names to C types (as used by the
#: PolyBench reference implementations).
P_TYPE_TO_CTYPE = {
    "p_float64": "double",
    "p_float32": "float",
    "p_int32": "int",
    "p_int64": "long long",
    "p_uint8": "unsigned char",
    "p_uint16": "unsigned short",
    "p_uint32": "unsigned int",
    "p_int8": "signed char",
    "p_int16": "short",
}


class Harness(ABC):
    """Strategy object that generates the measurement wrapper code."""

    name: str = "abstract"

    @abstractmethod
    def generate_wrappers(self, program: "TiramisuProgram") -> dict[str, str]:
        """Return ``{"cpp": ..., "h": ...}`` wrapper sources for `program`."""


class DefaultHarness(Harness):
    """TiraLib's historical harness (random init, warm in-process timing)."""

    name = "default"

    def generate_wrappers(self, program: "TiramisuProgram") -> dict[str, str]:
        buffers_init_lines = ""
        for i, buffer_name in enumerate(program.IO_buffer_names):
            size_expr = "*".join(program.buffer_sizes[i][::-1])
            dims_expr = ",".join(program.buffer_sizes[i][::-1])
            buffers_init_lines += f"""
    double *c_{buffer_name} = (double*)malloc({size_expr}* sizeof(double));
    parallel_init_buffer(c_{buffer_name}, {size_expr}, (double){str(random.randint(1, 10))});
    Halide::Buffer<double> {buffer_name}(c_{buffer_name}, {dims_expr});
    """  # noqa: E501

        wrapper_cpp_code = wrapper_cpp_template.replace(
            "$func_id$", program.temp_files_identifier
        ).replace("$func_name$", program.name)
        wrapper_cpp_code = wrapper_cpp_code.replace(
            "$buffers_init$", buffers_init_lines
        )
        wrapper_cpp_code = wrapper_cpp_code.replace(
            "$func_params$",
            ",".join([name + ".raw_buffer()" for name in program.IO_buffer_names]),
        )

        wrapper_h_code = wrapper_h_template.replace("$func_name$", program.name)
        wrapper_h_code = wrapper_h_code.replace(
            "$func_params$",
            ",".join(["halide_buffer_t *" + name for name in program.IO_buffer_names]),
        )

        return {
            "cpp": wrapper_cpp_code,
            "h": wrapper_h_code,
        }


class PolybenchHarness(Harness):
    """PolyBench/C 4.2.1 compatible measurement harness.

    Parameters
    ----------
    `init_sidecar_path` : str | Path
        Path to the per-benchmark init sidecar header (generated by
        ``polybench_tiramisu``'s ``generate_polybench_init_sidecars.py``).
        The sidecar must define::

            static void tiralib_polybench_init_arrays(<typed buffer ptrs>);
            static void tiralib_polybench_dump_arrays(<typed buffer ptrs>);

        taking the program's I/O buffers (flat pointers) in
        ``tiramisu::codegen`` order.
    `cache_size_kb` : int | None
        Cache size flushed before each measurement, in kB. ``None`` keeps
        PolyBench's default (``POLYBENCH_CACHE_SIZE_KB`` = 32770, ~33MB).
    `flush_cache` : bool
        If False, defines ``POLYBENCH_NO_FLUSH_CACHE`` (PolyBench flushes
        by default).
    `linux_fifo_scheduler` : bool
        If True, defines ``POLYBENCH_LINUX_FIFO_SCHEDULER`` (requires
        running as root, see PolyBench documentation).

    Notes
    -----
    Measurement semantics under this harness:

    - ``min_runs``/``max_runs`` count *process-level* measurements: each
      measurement runs in a freshly exec'ed process (PolyBench runs one
      kernel per process; ``time_benchmark.sh`` re-runs the binary).
    - ``time_budget`` (ms) is enforced between measurements after the
      first ``min_runs``; a measurement in flight past the budget is
      killed (its time is discarded), matching the default harness.
    - Times are printed in **milliseconds** (TiraLib's unit convention)
      computed as ``(polybench_t_end - polybench_t_start) * 1000``; the
      timer itself is PolyBench's own (``gettimeofday``-based
      ``rtclock``, preceded by the PolyBench cache flush).
    - Setting the ``TIRALIB_DUMP_ARRAYS`` environment variable makes the
      first measurement dump the live-out arrays to stderr in PolyBench's
      ``POLYBENCH_DUMP_ARRAYS`` format (for correctness checking against
      the reference PolyBench/C implementation).
    """

    name = "polybench"

    def __init__(
        self,
        init_sidecar_path: str | Path | None = None,
        cache_size_kb: int | None = None,
        flush_cache: bool = True,
        linux_fifo_scheduler: bool = False,
        *,
        init_sidecar_code: str | None = None,
    ):
        if (init_sidecar_path is None) == (init_sidecar_code is None):
            raise ValueError(
                "PolybenchHarness requires exactly one of init_sidecar_path "
                "or init_sidecar_code"
            )
        self.cache_size_kb = cache_size_kb
        self.flush_cache = flush_cache
        self.linux_fifo_scheduler = linux_fifo_scheduler

        if init_sidecar_path is not None:
            self.init_sidecar_path = Path(init_sidecar_path)
            if not self.init_sidecar_path.exists():
                raise FileNotFoundError(
                    f"PolybenchHarness init sidecar not found: {self.init_sidecar_path}"
                )
            sidecar_code = self.init_sidecar_path.read_text()
            origin = str(self.init_sidecar_path)
        else:
            self.init_sidecar_path = None
            assert init_sidecar_code is not None
            sidecar_code = init_sidecar_code
            origin = "<in-memory sidecar>"

        for required in (
            "tiralib_polybench_init_arrays",
            "tiralib_polybench_dump_arrays",
        ):
            if required not in sidecar_code:
                raise ValueError(
                    f"Init sidecar {origin} does not define "
                    f"'{required}'. Was it generated by "
                    "generate_polybench_init_sidecars.py?"
                )
        self.sidecar_code = sidecar_code

    @classmethod
    def from_code(cls, init_sidecar_code: str, **options) -> "PolybenchHarness":
        """Build a harness from sidecar *content* rather than a file path.

        Useful when the benchmark sources come from an archive (e.g. the
        sidecar was read out of a zip next to the generator .cpp).
        `options` are forwarded to the constructor (cache_size_kb, ...).
        """
        return cls(init_sidecar_code=init_sidecar_code, **options)

    @classmethod
    def detect(
        cls, generator_file_path: str | Path, function_name: str
    ) -> "PolybenchHarness | None":
        """Detect a sidecar next to a generator file.

        Returns a :class:`PolybenchHarness` if
        ``<generator dir>/<function_name>_init.h`` exists, else None.
        """
        sidecar = Path(generator_file_path).parent / f"{function_name}_init.h"
        if sidecar.exists():
            logger.info(
                "PolyBench init sidecar found (%s): using PolybenchHarness",
                sidecar,
            )
            return cls(sidecar)
        return None

    def _polybench_sources(self) -> tuple[str, str]:
        polybench_h = (_POLYBENCH_DIR / "polybench.h").read_text()
        polybench_c = (_POLYBENCH_DIR / "polybench.c").read_text()
        # The sources are inlined into a single translation unit: drop the
        # self-include (everything it needs is pasted right above it).
        polybench_c = re.sub(
            r'#\s*include\s+"polybench\.h"',
            "// (polybench.h inlined above)",
            polybench_c,
        )
        return polybench_h, polybench_c

    def _buffer_ctypes(self, program: "TiramisuProgram") -> list[str]:
        p_types = getattr(program, "buffer_types", None)
        if not p_types:
            p_types = ["p_float64"] * len(program.IO_buffer_names)
        ctypes = []
        for p_type in p_types:
            if p_type not in P_TYPE_TO_CTYPE:
                raise ValueError(f"PolybenchHarness: unsupported buffer type {p_type}")
            ctypes.append(P_TYPE_TO_CTYPE[p_type])
        return ctypes

    def generate_wrappers(self, program: "TiramisuProgram") -> dict[str, str]:
        polybench_h, polybench_c = self._polybench_sources()
        ctypes = self._buffer_ctypes(program)

        defines = ["#define POLYBENCH_TIME 1"]
        if self.cache_size_kb is not None:
            defines.append(f"#define POLYBENCH_CACHE_SIZE_KB {self.cache_size_kb}")
        if not self.flush_cache:
            defines.append("#define POLYBENCH_NO_FLUSH_CACHE 1")
        if self.linux_fifo_scheduler:
            defines.append("#define POLYBENCH_LINUX_FIFO_SCHEDULER 1")

        buffers_decl = ""
        buffers_free = ""
        for name, sizes, ctype in zip(
            program.IO_buffer_names, program.buffer_sizes, ctypes
        ):
            size_expr = "*".join(sizes)
            # Halide dims are innermost-first: reverse the declared sizes.
            dims_expr = ",".join(sizes[::-1])
            buffers_decl += (
                f"    {ctype} *c_{name} = ({ctype}*) polybench_alloc_data"
                f"({size_expr}, sizeof({ctype}));\n"
                f"    Halide::Buffer<{ctype}> {name}(c_{name}, {dims_expr});\n"
            )
            buffers_free += f"    free((void*)c_{name});\n"

        c_ptr_args = ", ".join(f"c_{name}" for name in program.IO_buffer_names)
        func_params = ",".join(
            name + ".raw_buffer()" for name in program.IO_buffer_names
        )

        wrapper_cpp_code = (
            polybench_wrapper_cpp_template.replace(
                "$polybench_defines$", "\n".join(defines)
            )
            .replace("$polybench_h$", polybench_h)
            .replace("$polybench_c$", polybench_c)
            .replace("$init_sidecar$", self.sidecar_code)
            .replace("$func_id$", program.temp_files_identifier)
            .replace("$func_name$", program.name)
            .replace("$buffers_decl$", buffers_decl)
            .replace("$buffers_free$", buffers_free)
            .replace("$c_ptr_args$", c_ptr_args)
            .replace("$func_params$", func_params)
        )

        wrapper_h_code = polybench_wrapper_h_template.replace(
            "$func_name$", program.name
        ).replace(
            "$func_params$",
            ",".join("halide_buffer_t *" + name for name in program.IO_buffer_names),
        )

        return {
            "cpp": wrapper_cpp_code,
            "h": wrapper_h_code,
        }


def polybench_normalized_time(
    times: list[float], variance_accepted: float = 5.0
) -> tuple[float, float]:
    """Normalize measurements the way PolyBench's ``time_benchmark.sh`` does.

    Sorts the measurements, discards the smallest and largest, and returns
    the arithmetic mean of the remaining ones together with the maximal
    deviation from that mean in percent. PolyBench runs the benchmark 5
    times and averages the middle 3; pass 5 measurements to reproduce that
    exactly.

    Logs a warning (like the script) if the deviation exceeds
    `variance_accepted` percent.

    Returns
    -------
    ``(normalized_time, max_deviation_percent)``
    """
    if len(times) < 3:
        raise ValueError(
            "polybench_normalized_time needs at least 3 measurements "
            f"(got {len(times)}); PolyBench uses 5"
        )
    middle = sorted(times)[1:-1]
    mean = sum(middle) / len(middle)
    max_dev = max(abs(t - mean) for t in middle)
    variance = (max_dev / mean) * 100 if mean != 0 else 0.0
    if variance >= variance_accepted:
        logger.warning(
            "Variance is above threshold, unsafe performance measurement "
            "=> max deviation=%.5f%%, tolerance=%s%%",
            variance,
            variance_accepted,
        )
    return mean, variance


# ---------------------------------------------------------------------------
# Default harness templates (TiraLib's historical wrapper)
# ---------------------------------------------------------------------------

wrapper_cpp_template = """#include "Halide.h"
#include "$func_id$_wrapper.h"
#include "tiramisu/utils.h"
#include <iostream>
#include <time.h>
#include <fstream>
#include <chrono>

using namespace std::chrono;
using namespace std;

int main(int, char **argv){

$buffers_init$

    // halide_set_num_threads(48);

    TuneParams params = get_tune_params();
    setup_signal_handler();

    bool use_budget = (params.time_budget_ms > 0);
    int limit = 0;

    // Determine loop iteration limit.
    // If budget is unset, run exactly min_runs.
    // If budget is set, run up to max_runs, but correct for cases where max_runs < min_runs.
    if (!use_budget) {
        limit = params.min_runs;
    } else {
        limit = std::max(params.min_runs, params.max_runs);
    }

    double duration;
    auto total_start = std::chrono::high_resolution_clock::now();

    for (int i = 0; i < limit; ++i) {

        bool timer_active = false;

        // Initiate timeout logic only if the mandatory minimum runs are satisfied.
        if (use_budget && i >= params.min_runs) {

            auto now = std::chrono::high_resolution_clock::now();
            double total_elapsed_ms = std::chrono::duration_cast<std::chrono::nanoseconds>(now - total_start).count() / 1000000.0;
            double remaining_ms = params.time_budget_ms - total_elapsed_ms;

            // Abort if budget is exhausted between runs.
            if (remaining_ms <= 0.0) {
                break;
            }

            // Ensure timer value is non-zero to prevent inadvertent disablement.
            if (remaining_ms < 0.001) remaining_ms = 0.001;

            set_execution_timer(remaining_ms);
            timer_active = true;
        }

        auto begin = std::chrono::high_resolution_clock::now();
        $func_name$($func_params$);
        auto end = std::chrono::high_resolution_clock::now();

        // Disarm timer immediately post-execution to protect I/O operations.
        if (timer_active) {
            clear_execution_timer();
        }

        duration = std::chrono::duration_cast<std::chrono::nanoseconds>(end-begin).count() / (double)1000000;
        std::cout << duration << " " << std::flush;
    }

    std::cout << std::endl;
    return 0;
}"""  # noqa: E501

wrapper_h_template = """#include <tiramisu/utils.h>
#include <sys/time.h>
#include <unistd.h>
#include <signal.h>
#include <cstdlib>
#include <algorithm>
#include <vector>
#include <string>
#include <limits>
#include <iostream>

#define NB_THREAD_INIT 48

struct args {
    double *buf;
    unsigned long long int part_start;
    unsigned long long int part_end;
    double value;
};

// Configuration parameters for execution scheduling
struct TuneParams {
    int min_runs;
    int max_runs;
    double time_budget_ms; // -1.0 indicates no budget constraint
};

void *init_part(void *params)
{
   double *buffer = ((struct args*) params)->buf;
   unsigned long long int start = ((struct args*) params)->part_start;
   unsigned long long int end = ((struct args*) params)->part_end;
   double val = ((struct args*) params)->value;
   for (unsigned long long int k = start; k < end; k++){
       buffer[k]=val;
   }
   pthread_exit(NULL);
}

void parallel_init_buffer(double* buf, unsigned long long int size, double value){
    pthread_t threads[NB_THREAD_INIT];
    struct args params[NB_THREAD_INIT];
    for (int i = 0; i < NB_THREAD_INIT; i++) {
        unsigned long long int start = i*size/NB_THREAD_INIT;
        unsigned long long int end = std::min((i+1)*size/NB_THREAD_INIT, size);
        params[i] = (struct args){buf, start, end, value};
        pthread_create(&threads[i], NULL, init_part, (void*)&(params[i]));
    }
    for (int i = 0; i < NB_THREAD_INIT; i++)
        pthread_join(threads[i], NULL);
    return;
}

#ifdef __cplusplus
extern "C" {
#endif
int $func_name$($func_params$);
#ifdef __cplusplus
}  // extern "C"
#endif

// Parses environment variables to configure tuning parameters
TuneParams get_tune_params() {
    TuneParams params;

    // Parse MIN_RUNS. Defaults to 0 if undefined.
    const char* min_runs_env = std::getenv("MIN_RUNS");
    params.min_runs = (min_runs_env != nullptr) ? std::stoi(min_runs_env) : 0;

    // Parse TIME_BUDGET. Defaults to -1.0 (infinite) if undefined.
    const char* budget_env = std::getenv("TIME_BUDGET");
    if (budget_env != nullptr) {
        params.time_budget_ms = std::stof(budget_env);
    } else {
        params.time_budget_ms = -1.0;
    }

    // Parse MAX_RUNS. Defaults to INT_MAX if undefined or "inf".
    const char* max_runs_env = std::getenv("MAX_RUNS");
    if (max_runs_env != nullptr && std::string(max_runs_env) != "inf") {
        params.max_runs = std::stoi(max_runs_env);
    } else {
        params.max_runs = std::numeric_limits<int>::max();
    }

    return params;
}

// Handler for SIGALRM.
// Invokes _exit() to immediately terminate the process when the time budget is exceeded.
// Partial results have already been flushed to stdout.
void timer_handler(int signum) {
    _exit(0);
}

// Configures the SIGALRM handler.
void setup_signal_handler() {
    struct sigaction sa;
    sa.sa_handler = timer_handler;
    sigemptyset(&sa.sa_mask);
    sa.sa_flags = 0;
    sigaction(SIGALRM, &sa, NULL);
}

// Arms the OS timer for the specified duration (milliseconds).
void set_execution_timer(double time_left_ms) {
    if (time_left_ms <= 0) return;

    struct itimerval timer;
    long seconds = (long)(time_left_ms / 1000.0);
    long useconds = (long)((time_left_ms - (seconds * 1000.0)) * 1000.0);

    timer.it_value.tv_sec = seconds;
    timer.it_value.tv_usec = useconds;

    // Non-repeating timer
    timer.it_interval.tv_sec = 0;
    timer.it_interval.tv_usec = 0;

    setitimer(ITIMER_REAL, &timer, NULL);
}

// Disarms the OS timer to prevent interruption during non-execution phases.
void clear_execution_timer() {
    struct itimerval timer;
    timer.it_value.tv_sec = 0;
    timer.it_value.tv_usec = 0;
    timer.it_interval.tv_sec = 0;
    timer.it_interval.tv_usec = 0;
    setitimer(ITIMER_REAL, &timer, NULL);
}
"""  # noqa: E501


# ---------------------------------------------------------------------------
# PolyBench harness templates
# ---------------------------------------------------------------------------

# The wrapper is a single self-contained translation unit:
#   1. PolyBench compile-time options (POLYBENCH_TIME, ...)
#   2. vendored polybench.h + polybench.c, inlined verbatim
#   3. the per-benchmark init sidecar (PolyBench init_array/print_array,
#      extracted verbatim from PolyBench/C, operating on flat buffers)
#   4. a main() that runs each measurement in a freshly exec'ed process,
#      PolyBench-style: aligned alloc -> init_array -> cache flush + timer
#      start -> one kernel call -> timer stop -> print time.
# Being self-contained keeps it compatible with both wrapper build paths
# (CompilingService and TiraLibCpp's compile_wrapper) without flag changes.
polybench_wrapper_cpp_template = """// TiraLib PolyBench-mode measurement wrapper (auto-generated).
// Measurement methodology: PolyBench/C 4.2.1 (see inlined polybench.c).
$polybench_defines$

// ===== begin inlined polybench.h (vendored, verbatim) =====
$polybench_h$
// ===== end inlined polybench.h =====

// ===== begin inlined polybench.c (vendored, verbatim) =====
$polybench_c$
// ===== end inlined polybench.c =====

// ===== begin per-benchmark init sidecar =====
$init_sidecar$
// ===== end per-benchmark init sidecar =====

#include "Halide.h"
#include "$func_id$_wrapper.h"
#include <cerrno>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <limits>
#include <string>
#include <signal.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>

namespace {

struct TuneParams {
    int min_runs;
    int max_runs;
    double time_budget_ms; // -1.0 indicates no budget constraint
};

// Parses environment variables to configure tuning parameters
// (same protocol as the default TiraLib harness).
TuneParams get_tune_params() {
    TuneParams params;

    const char* min_runs_env = std::getenv("MIN_RUNS");
    params.min_runs = (min_runs_env != nullptr) ? std::stoi(min_runs_env) : 0;

    const char* budget_env = std::getenv("TIME_BUDGET");
    params.time_budget_ms =
        (budget_env != nullptr) ? std::stof(budget_env) : -1.0;

    const char* max_runs_env = std::getenv("MAX_RUNS");
    if (max_runs_env != nullptr && std::string(max_runs_env) != "inf") {
        params.max_runs = std::stoi(max_runs_env);
    } else {
        params.max_runs = std::numeric_limits<int>::max();
    }

    return params;
}

// One PolyBench-style measurement, meant to run in a fresh process.
int run_single_measurement(bool dump_arrays) {
    // Allocation via polybench_alloc_data: 4096-byte aligned, PolyBench
    // inter-array padding semantics.
$buffers_decl$

    // Deterministic PolyBench init_array initialization (sidecar).
    tiralib_polybench_init_arrays($c_ptr_args$);

    // polybench_timer_start() == polybench_prepare_instruments()
    // (cache flush / FIFO scheduler as configured) + timer start.
    polybench_timer_start();
    $func_name$($func_params$);
    polybench_timer_stop();

    // PolyBench prints seconds; TiraLib's protocol is milliseconds.
    // The measured interval is PolyBench's own (rtclock/gettimeofday).
    std::printf("%0.6f ", (polybench_t_end - polybench_t_start) * 1000.0);
    std::fflush(stdout);

    if (dump_arrays) {
        // Live-out arrays, PolyBench POLYBENCH_DUMP_ARRAYS format, stderr.
        tiralib_polybench_dump_arrays($c_ptr_args$);
        std::fflush(stderr);
    }

$buffers_free$
    return 0;
}

volatile pid_t g_child_pid = 0;
volatile sig_atomic_t g_budget_expired = 0;

// SIGALRM => time budget exhausted: kill the in-flight measurement.
// Its time was not printed yet, so it is simply discarded.
void budget_alarm_handler(int) {
    g_budget_expired = 1;
    pid_t child = g_child_pid;
    if (child > 0) {
        kill(child, SIGKILL);
    }
}

void arm_budget_timer(double time_left_ms) {
    if (time_left_ms <= 0) return;
    struct itimerval timer;
    long seconds = (long)(time_left_ms / 1000.0);
    long useconds = (long)((time_left_ms - (seconds * 1000.0)) * 1000.0);
    timer.it_value.tv_sec = seconds;
    timer.it_value.tv_usec = useconds;
    timer.it_interval.tv_sec = 0;
    timer.it_interval.tv_usec = 0;
    setitimer(ITIMER_REAL, &timer, NULL);
}

void disarm_budget_timer() {
    struct itimerval timer;
    timer.it_value.tv_sec = 0;
    timer.it_value.tv_usec = 0;
    timer.it_interval.tv_sec = 0;
    timer.it_interval.tv_usec = 0;
    setitimer(ITIMER_REAL, &timer, NULL);
}

} // namespace

int main(int argc, char **argv) {
    // Child mode: perform exactly one measurement, then exit. This is how
    // each measurement gets a fresh process, like PolyBench's
    // time_benchmark.sh re-running the benchmark binary.
    if (argc > 1 && std::strcmp(argv[1], "--tiralib-single-run") == 0) {
        bool dump = (argc > 2 && std::strcmp(argv[2], "--dump") == 0);
        return run_single_measurement(dump);
    }

    TuneParams params = get_tune_params();
    bool use_budget = (params.time_budget_ms > 0);
    int limit = use_budget ? std::max(params.min_runs, params.max_runs)
                           : params.min_runs;
    bool dump_requested = (std::getenv("TIRALIB_DUMP_ARRAYS") != nullptr);

    struct sigaction sa;
    sa.sa_handler = budget_alarm_handler;
    sigemptyset(&sa.sa_mask);
    sa.sa_flags = 0; // no SA_RESTART: waitpid must be interruptible
    sigaction(SIGALRM, &sa, NULL);

    auto total_start = std::chrono::high_resolution_clock::now();

    for (int i = 0; i < limit; ++i) {
        bool timer_active = false;
        double remaining_ms = 0.0;

        // Budget only applies once the mandatory min_runs are done.
        if (use_budget && i >= params.min_runs) {
            auto now = std::chrono::high_resolution_clock::now();
            double total_elapsed_ms =
                std::chrono::duration_cast<std::chrono::nanoseconds>(
                    now - total_start).count() / 1000000.0;
            remaining_ms = params.time_budget_ms - total_elapsed_ms;
            if (remaining_ms <= 0.0) {
                break;
            }
            if (remaining_ms < 0.001) remaining_ms = 0.001;
            timer_active = true;
        }

        pid_t pid = fork();
        if (pid < 0) {
            std::perror("tiralib polybench wrapper: fork");
            return 1;
        }
        if (pid == 0) {
            // Fresh process per measurement: re-exec ourselves.
            bool dump = dump_requested && i == 0;
            if (dump) {
                execl(argv[0], argv[0], "--tiralib-single-run", "--dump",
                      (char *)NULL);
                execl("/proc/self/exe", argv[0], "--tiralib-single-run",
                      "--dump", (char *)NULL);
            } else {
                execl(argv[0], argv[0], "--tiralib-single-run", (char *)NULL);
                execl("/proc/self/exe", argv[0], "--tiralib-single-run",
                      (char *)NULL);
            }
            std::perror("tiralib polybench wrapper: execl");
            _exit(127);
        }

        g_child_pid = pid;
        if (timer_active) {
            arm_budget_timer(remaining_ms);
        }

        int status = 0;
        while (waitpid(pid, &status, 0) < 0 && errno == EINTR) {
            // Interrupted by SIGALRM: the handler killed the child;
            // retry to reap it.
        }
        g_child_pid = 0;
        if (timer_active) {
            disarm_budget_timer();
        }

        if (WIFSIGNALED(status)) {
            if (g_budget_expired) {
                // In-flight measurement killed by the time budget:
                // stop measuring, keep what was already printed.
                break;
            }
            // Genuine crash (e.g. segfault in the kernel): propagate.
            std::fprintf(stderr,
                         "tiralib polybench wrapper: measurement killed by "
                         "signal %d\\n", WTERMSIG(status));
            return 1;
        }
        if (WIFEXITED(status) && WEXITSTATUS(status) != 0) {
            return WEXITSTATUS(status);
        }
        if (g_budget_expired) {
            break;
        }
    }

    std::printf("\\n");
    std::fflush(stdout);
    return 0;
}"""  # noqa: E501

# The wrapper header is included both by the wrapper TU and by the
# generated schedule TU (the Tiramisu generator re-enables its wrapper
# include), so it must stay minimal and benign in both contexts.
polybench_wrapper_h_template = """#include <tiramisu/utils.h>

#ifdef __cplusplus
extern "C" {
#endif
int $func_name$($func_params$);
#ifdef __cplusplus
}  // extern "C"
#endif
"""
                                                                                                                                                                                   