import json
import random
import re
import string
from typing import Any

from tiralib.tiramisu.compiling_service import CompilingService
from tiralib.tiramisu.function_server import FunctionServer
from tiralib.tiramisu.harness import (
    DefaultHarness,
    Harness,
    PolybenchHarness,
    wrapper_cpp_template,  # noqa: F401  (re-exported for backward compat)
    wrapper_h_template,  # noqa: F401  (re-exported for backward compat)
)
from tiralib.tiramisu.tiramisu_tree import TiramisuTree


class TiramisuProgram:
    """This class represents a tiramisu function. It contains all the neccessary
    information about the function to be able to generate the code for it.

    Attributes
    ----------
    `name`: str
        The name of the function
    `temp_files_identifier`: str
        A unique name with random suffix used to differentiate between temporary
        files generated by concurrently running instances of TiraLib
    `cpp_code`: str
        The code of the function
    `tree`: TiramisuTree
        The tree of the function
    `IO_buffer_names`: list[str]
        The names of the input/output buffers
    `buffer_sizes`: list[list[str]]
        The sizes of the input/output buffers
    `annotations`: Dict
        The annotations of the function
    `isl_ast_string`: str
        The isl ast of the function
    `wrapper_obj`: bytes
        The wrapper object of the function
    `server`: FunctionServer
        TiralibCpp server object
    `harness`: Harness
        The measurement harness used to generate the execution wrapper.
        Defaults to :class:`DefaultHarness`; PolyBench-derived programs
        with an init sidecar next to their generator file are
        auto-detected and get a :class:`PolybenchHarness` (see
        `from_file`).
    """

    def __init__(self: "TiramisuProgram"):
        self.name: str
        self.temp_files_identifier: str
        self.cpp_code: str
        self.tree: TiramisuTree
        self.IO_buffer_names: list[str]
        self.buffer_sizes: list[list[str]]
        self.buffer_types: list[str] = []
        self.annotations: dict[str, Any] | None = None
        self.isl_ast_string: str | None = None
        self.wrapper_obj: bytes | None = None
        self.server: FunctionServer | None = None
        self.harness: Harness = DefaultHarness()

    @property
    def wrappers(self):
        return self.harness.generate_wrappers(self)

    @classmethod
    def from_annotations(
        cls,
        annotations: dict[str, Any],
        cpp_code: str,
        load_tree: bool = True,
        wrapper_obj: bytes | None = None,
        harness: Harness | None = None,
    ) -> "TiramisuProgram":
        # Initiate an instante of the TiramisuProgram class
        tiramisu_prog = cls()
        tiramisu_prog.cpp_code = cpp_code
        tiramisu_prog.annotations = annotations
        tiramisu_prog.load_code_lines()
        if harness is not None:
            tiramisu_prog.harness = harness

        if wrapper_obj:
            tiramisu_prog.wrapper_obj = wrapper_obj

        if load_tree:
            tiramisu_prog.tree = TiramisuTree.from_annotations(
                tiramisu_prog.annotations
            )
        return tiramisu_prog

    @classmethod
    def from_file(
        cls,
        file_path: str,
        load_annotations: bool = False,
        load_isl_ast: bool = False,
        load_tree: bool = False,
        harness: Harness | None = None,
    ) -> "TiramisuProgram":
        """This function loads a tiramisu function from its cpp file and its
        wrapper files.

        Parameters
        ----------
        `file_path`: str
            The path to the cpp file of the tiramisu function
        `load_annotations`: bool
            A flag to indicate if the annotations should be loaded or not
        `load_isl_ast`: bool
            A flag to indicate if the isl ast should be loaded or not
        `load_tree`: bool
            A flag to indicate if the tree should be constructed or not
        `harness`: Harness or None
            The measurement harness to use when executing the program. If
            None (default), a PolyBench init sidecar
            (``<function_name>_init.h``) is looked up next to `file_path`;
            if found, a :class:`PolybenchHarness` is used, otherwise the
            :class:`DefaultHarness`.

        Returns
        -------
        `tiramisu_prog`: TiramisuProgram
            An instance of the TiramisuProgram class
        """
        # Initiate an instante of the TiramisuProgram class

        tiramisu_prog = cls()
        with open(file_path, "r") as f:
            tiramisu_prog.cpp_code = f.read()
        tiramisu_prog.load_code_lines()

        if harness is None:
            harness = PolybenchHarness.detect(file_path, tiramisu_prog.name)
        if harness is not None:
            tiramisu_prog.harness = harness

        if load_annotations:
            tiramisu_prog.annotations = json.loads(
                CompilingService.compile_annotations(tiramisu_prog)
            )
        elif load_isl_ast:
            tiramisu_prog.isl_ast_string = CompilingService.compile_isl_ast_tree(
                tiramisu_prog
            )

        if load_tree:
            if tiramisu_prog.annotations:
                assert tiramisu_prog.annotations is not None
                tiramisu_prog.tree = TiramisuTree.from_annotations(
                    tiramisu_prog.annotations
                )
            elif tiramisu_prog.isl_ast_string:
                tiramisu_prog.tree = TiramisuTree.from_isl_ast_string_list(
                    tiramisu_prog.isl_ast_string.split("\n")
                )
            else:
                raise Exception(
                    "You should load either the annotations or the isl ast\
                    string to load the tree"
                )

        # After taking the neccessary fields return the instance
        return tiramisu_prog

    @classmethod
    def init_server(
        cls,
        cpp_code: str,
        load_annotations: bool = False,
        load_isl_ast: bool = False,
        load_tree: bool = False,
        reuse_server: bool = False,
        harness: Harness | None = None,
    ) -> "TiramisuProgram":
        # Initiate an instante of the TiramisuProgram class
        tiramisu_prog = cls()
        tiramisu_prog.cpp_code = cpp_code
        tiramisu_prog.load_code_lines()
        # The harness must be set before creating the server: the server
        # writes the harness-generated wrapper files at construction time.
        if harness is not None:
            tiramisu_prog.harness = harness
        tiramisu_prog.server = FunctionServer(tiramisu_prog, reuse_server=reuse_server)

        if load_annotations:
            annotations_str = tiramisu_prog.server.get_annotations()
            tiramisu_prog.annotations = json.loads(annotations_str)
        elif load_isl_ast:
            result = tiramisu_prog.server.run()
            tiramisu_prog.isl_ast_string = result.isl_ast

        if load_tree:
            if tiramisu_prog.annotations:
                assert tiramisu_prog.annotations is not None
                tiramisu_prog.tree = TiramisuTree.from_annotations(
                    tiramisu_prog.annotations
                )
            elif tiramisu_prog.isl_ast_string:
                tiramisu_prog.tree = TiramisuTree.from_isl_ast_string_list(
                    tiramisu_prog.isl_ast_string.split("\n")
                )
            else:
                raise Exception(
                    "You should load either the annotations or the isl ast \
                    string to load the tree"
                )

        # After taking the neccessary fields return the instance
        return tiramisu_prog

    def load_code_lines(self):
        """This function loads the file code , it is necessary to generate
        legality check code and annotations
        """
        self.name = re.findall(r"tiramisu::init\(\"(\w+)\"\);", self.cpp_code)[0]
        self.temp_files_identifier = (
            self.name
            + "_"
            + "".join(random.choices(string.ascii_letters + string.digits, k=5))
        )
        self.body = re.findall(
            r"int main\([\w\s,*]+\)\s*\{([\W\w\s]*)tiramisu::codegen",
            self.cpp_code,
        )[0]
        # Remove the wrapper include from the original string
        self.wrapper_str = f'#include "{self.temp_files_identifier}_wrapper.h"'
        self.cpp_code = self.cpp_code.replace(
            f'#include "{self.name}_wrapper.h"', f"// {self.wrapper_str}"
        )
        # Change the file name of the generated object file in the codegen line to use the temp files identifier
        self.cpp_code = re.sub(
            r'(tiramisu::codegen\(\{[^}]+\},\s*")([^"]*)("\);)',
            r"\1" + f"./{self.temp_files_identifier}.o" + r"\3",
            self.cpp_code,
        )
        self.code_gen_line: str = re.findall(r"tiramisu::codegen\({.+;", self.cpp_code)[
            0
        ]
        buffers_vect = re.findall(r"{(.+)}", self.code_gen_line)[0]
        self.IO_buffer_names = re.findall(r"\w+", buffers_vect)
        self.buffer_sizes = []
        self.buffer_types = []
        for buf_name in self.IO_buffer_names:
            # Anchor on the opening parenthesis so that e.g. b_A does not
            # match the declaration of b_AB.
            buffer_decl = re.findall(
                r"buffer\s+" + buf_name + r"\s*\(.*", self.cpp_code
            )[0]
            sizes_vect = re.findall(r"{(.*)}", buffer_decl)[0]
            self.buffer_sizes.append(re.findall(r"\d+", sizes_vect))
            buffer_p_type = re.findall(r"(p_\w+)", buffer_decl)
            self.buffer_types.append(buffer_p_type[0] if buffer_p_type else "p_float64")

    def __str__(self) -> str:
        return f"TiramisuProgram(name={self.name})"

    def __repr__(self) -> str:
        return self.__str__()
